In [2]:
a = 3
assert a==3

In [3]:
def naive_relu(x):
    assert len(x.shape) == 2

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i,j], 0)
    
    return x

def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]

    return x

In [4]:
import numpy as np

x = np.array([1,2,3])
y = np.array([4,5,6])

z = x + y
z_ = np.maximum(z, 0)

In [5]:
print(z_)

[5 7 9]


In [7]:
# example of boradcasting

x = np.random.random((64,3,32,10))
y = np.random.random((32,10))

z = np.maximum(x, y)

print(x, y, z)

[[[[1.51976976e-01 5.23473006e-01 9.32427454e-01 ... 7.30646023e-01
    2.17885508e-01 9.82559436e-01]
   [2.03235623e-01 2.85371997e-01 6.59421984e-01 ... 3.72277104e-01
    7.42728514e-01 9.05110019e-01]
   [1.78166335e-01 1.45881740e-01 9.11153607e-01 ... 4.81727700e-01
    4.72919636e-01 2.68902890e-01]
   ...
   [2.52090084e-01 8.57161126e-01 6.75415089e-01 ... 1.47764681e-01
    7.29586114e-01 6.30506955e-01]
   [5.40528675e-01 1.12154965e-01 3.78419094e-01 ... 9.42616864e-01
    7.89386872e-01 6.09381349e-01]
   [9.75351983e-01 9.00677187e-01 1.23416183e-02 ... 5.03098094e-01
    4.82810665e-02 3.01128991e-01]]

  [[5.26019770e-01 9.60428449e-02 8.55567553e-01 ... 4.01023404e-01
    6.81698545e-01 2.27434181e-02]
   [1.40245826e-02 2.85480129e-02 6.20801977e-01 ... 8.34672194e-01
    5.88903767e-01 7.49396866e-01]
   [4.89220504e-01 5.75485700e-01 7.89060207e-01 ... 2.56121565e-01
    4.65404539e-01 6.62633017e-01]
   ...
   [6.16501060e-01 6.86973758e-01 5.37668335e-01 ... 9.95

In [11]:
x = np.linspace(1,10, 10).reshape(2,-1)
print(x)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
